// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Client struct {
	ID           int64
	FirstName    string
	LastName     string
	EmailAddress string
	PhoneNumber  string
}

type ClientInspection struct {
	ClientID     sql.NullInt64
	InspectionID sql.NullInt64
}

type ClientPropertyInterest struct {
	ClientID   sql.NullInt64
	PropertyID sql.NullInt64
}

type Contract struct {
	ID                    int64
	PropertyID            int64
	ListingTypeID         int64
	ContractDocument      string
	ResponsibleEmployeeID int64
	ClientID              int64
	ContractStatusID      int64
	SignedDate            time.Time
	StartDate             time.Time
	EndDate               time.Time
}

type ContractStatus struct {
	ID          int64
	Description string
}

type Employee struct {
	ID        int64
	FirstName string
	LastName  string
	StartDate time.Time
	EndDate   sql.NullTime
	JobTitle  string
}

type Feature struct {
	ID          int64
	FeatureName string
}

type Inspection struct {
	ID                    int64
	PropertyID            int64
	InspectionDatetime    time.Time
	ResponsibleEmployeeID int64
}

type Listing struct {
	ID              int64
	PropertyID      int64
	ListingStatusID int64
	ListingTypeID   int64
	Price           int64
	CreatedDate     time.Time
}

type ListingStatus struct {
	ID          int64
	Description string
}

type ListingType struct {
	ID          int64
	Description string
}

type Offer struct {
	ID            int64
	ClientID      int64
	PropertyID    int64
	OfferStatusID int64
	OfferAmount   int64
}

type OfferStatus struct {
	ID          int64
	Description string
}

type Property struct {
	ID             int64
	AddressLine1   string
	AddressLine2   sql.NullString
	City           string
	Region         string
	PropertyTypeID int64
	PropertySize   int64
	BlockSize      int64
	NumBedrooms    int64
	NumBathrooms   int64
	NumCarspaces   int64
	Description    sql.NullString
}

type PropertyEmployee struct {
	PropertyID sql.NullInt64
	EmployeeID sql.NullInt64
	RoleTypeID sql.NullInt64
	StartDate  time.Time
	EndDate    sql.NullTime
}

type PropertyFeature struct {
	PropertyID sql.NullInt64
	FeatureID  sql.NullInt64
}

type PropertyType struct {
	ID          int64
	Description string
}

type RoleType struct {
	ID          int64
	Description string
}
